test_that("feed conversion efficiency", {
  expect_warning(fce(ibw=1,fbw=0,fi=3,dm=4))
  expect_warning(fce(ibw=1,fbw=2,fi=0,dm=4))
  expect_warning(fce(ibw=1,fbw=2,fi=3,dm=0))
  expect_warning(fce(ibw=-1,fbw=2,fi=3,dm=4))
  expect_warning(fce(ibw=1,fbw=-2,fi=3,dm=4))
  expect_warning(fce(ibw=1,fbw=2,fi=-3,dm=4))
  expect_warning(fce(ibw=1,fbw=2,fi=3,dm=-4))
  expect_error(fce(ibw=0, fbw=2, fi=3, dm=4))
  expect_error(fce(ibw=NA, fbw=2, fi=3, dm=4))
  expect_error(fce(ibw=1, fbw=NA, fi=3, dm=4))
  expect_error(fce(ibw=1, fbw=2, fi=NA, dm=4))
  expect_error(fce(ibw=1, fbw=2, fi=3, dm=NA))
  expect_error(fce(ibw= 'test', fbw=2, fi=3, dm=4))
  expect_error(fce(ibw=1, fbw= 'test', fi=3, dm=4))
  expect_error(fce(ibw=1, fbw=2, fi= 'test', dm=4))
  expect_error(fce(ibw=1, fbw=2, fi=3, dm= 'test'))
})
