test_that("feed conversion efficiency", {
  expect_warning(fce(m_start=1,m_end=0,fi=3,dm=4))
  expect_warning(fce(m_start=1,m_end=2,fi=0,dm=4))
  expect_warning(fce(m_start=1,m_end=2,fi=3,dm=0))
  expect_warning(fce(m_start=-1,m_end=2,fi=3,dm=4))
  expect_warning(fce(m_start=1,m_end=-2,fi=3,dm=4))
  expect_warning(fce(m_start=1,m_end=2,fi=-3,dm=4))
  expect_warning(fce(m_start=1,m_end=2,fi=3,dm=-4))
  expect_error(fce(m_start=0, m_end=2, fi=3, dm=4))
  expect_error(fce(m_start=NA, m_end=2, fi=3, dm=4))
  expect_error(fce(m_start=1, m_end=NA, fi=3, dm=4))
  expect_error(fce(m_start=1, m_end=2, fi=NA, dm=4))
  expect_error(fce(m_start=1, m_end=2, fi=3, dm=NA))
  expect_error(fce(m_start= 'test', m_end=2, fi=3, dm=4))
  expect_error(fce(m_start=1, m_end= 'test', fi=3, dm=4))
  expect_error(fce(m_start=1, m_end=2, fi= 'test', dm=4))
  expect_error(fce(m_start=1, m_end=2, fi=3, dm= 'test'))
})
