test_that( "nutrient retention", {
  
  expect_warning(retention(ibw=-1, fbw= 2, nut_start=3,nut_end=4))
  expect_warning(retention(ibw=1, fbw= -2, nut_start=3,nut_end=4))
  expect_warning(retention(ibw=1, fbw= 2, nut_start=-3,nut_end=4))
  expect_warning(retention(ibw=1, fbw= 2, nut_start=3,nut_end=-4))
  expect_warning(retention(ibw=0, fbw= 2, nut_start=3,nut_end=4))
  expect_warning(retention(ibw=1, fbw= 0, nut_start=3,nut_end=4))
  expect_warning(retention(ibw=1, fbw= 2, nut_start=0,nut_end=4))
  expect_warning(retention(ibw=1, fbw= 2, nut_start=3,nut_end=0))
  expect_error(retention(ibw= 'test', fbw= 2, nut_start=3,nut_end=4))
  expect_error(retention(ibw=1, fbw= 'test', nut_start=3,nut_end=4))
  expect_error(retention(ibw=1, fbw= 2, nut_start= 'test',nut_end=4))
  expect_error(retention(ibw=1, fbw= 2, nut_start=3,nut_end= 'test'))
  expect_error(retention(ibw=NA, fbw= 2, nut_start=3,nut_end=4))
  expect_error(retention(ibw=1, fbw= NA, nut_start=3,nut_end=4))
  expect_error(retention(ibw=1, fbw= 2, nut_start=NA,nut_end=4))
  expect_error(retention(ibw=1, fbw= 2, nut_start=3,nut_end=NA))
  expect_error(retention(ibw> fbw, nut_start=3,nut_end=4))
  expect_error(retention(ibw=1, fbw= 2, nut_start<nut_end))
})