test_that( "nutrient retention", {
  
  expect_warning(retention(m_start=-1, m_end= 2, nut_start=3,nut_end=4))
  expect_warning(retention(m_start=1, m_end= -2, nut_start=3,nut_end=4))
  expect_warning(retention(m_start=1, m_end= 2, nut_start=-3,nut_end=4))
  expect_warning(retention(m_start=1, m_end= 2, nut_start=3,nut_end=-4))
  expect_warning(retention(m_start=0, m_end= 2, nut_start=3,nut_end=4))
  expect_warning(retention(m_start=1, m_end= 0, nut_start=3,nut_end=4))
  expect_warning(retention(m_start=1, m_end= 2, nut_start=0,nut_end=4))
  expect_warning(retention(m_start=1, m_end= 2, nut_start=3,nut_end=0))
  expect_error(retention(m_start= 'test', m_end= 2, nut_start=3,nut_end=4))
  expect_error(retention(m_start=1, m_end= 'test', nut_start=3,nut_end=4))
  expect_error(retention(m_start=1, m_end= 2, nut_start= 'test',nut_end=4))
  expect_error(retention(m_start=1, m_end= 2, nut_start=3,nut_end= 'test'))
  expect_error(retention(m_start=NA, m_end= 2, nut_start=3,nut_end=4))
  expect_error(retention(m_start=1, m_end= NA, nut_start=3,nut_end=4))
  expect_error(retention(m_start=1, m_end= 2, nut_start=NA,nut_end=4))
  expect_error(retention(m_start=1, m_end= 2, nut_start=3,nut_end=NA))
  expect_error(retention(m_start> m_end, nut_start=3,nut_end=4))
  expect_error(retention(m_start=1, m_end= 2, nut_start<nut_end))
})