test_that("Absolute growth calcultion works", {
  expect_equal(ag(ibw = 1, fbw = 2), 1)
  expect_error(ag(ibw = 1, fbw = "test"))
  expect_error(ag(ibw = "test", fbw = 2))
  expect_error(ag(ibw = NA, fbw = 2))
  expect_error(ag(c(1,2), 3))
  expect_error(ag(ibw = 1, fbw = NA))
  expect_warning(ag(ibw = -1, fbw = 2))
  expect_warning(ag(ibw = 1, fbw = -2))
})
