test_that("relative feeding rate",{
  expect_equal(rfr(m_start=1, m_end=2, duration=3,1))
  expect_warning(rfr(m_start=1, m_end=0, duration=3))
  expect_warning(rfr(m_start=0,m_end=2,duration=3))
  expect_warning(rfr(m_start=-1,m_end=2,duration=3))
  expect_warning(rfr(m_start=1,m_end=-2,duration=3))
  expect_warning(rfr(m_start=1,m_end=2,duration=-3))
  expect_error(rfr(m_start=1,m_end=2,duration=0))
  expect_error(rfr(m_start= 'test',m_end=2,duration=3))
  expect_error(rfr(m_start=1,m_end= 'test',duration=3))
  expect_error(rfr(m_start=1,m_end=2,duration= 'test'))
  expect_error(rfr(m_start=na,m_end=2,duration=3))
  expect_error(rfr(m_start=1,m_end=na,duration=3))
  expect_error(rfr(m_start=1,m_end=2,duration=na))
})

